//
// Created by meszi on 2017.11.21..
//

#ifndef STRATEGO_CLICKACTIONTYPE_H
#define STRATEGO_CLICKACTIONTYPE_H

enum class ClickActionType {
    RESET_ACTION,
    EXIT_ACTION,
    NEXT_ACTION,
    SETUP_ACTION,
    BOARD_ACTION,
    CONTAINER_ACTION
};

#endif //STRATEGO_CLICKACTIONTYPE_H
